/**
 * flags.ts — Mapping nom d'équipe → code ISO 3166-1 alpha-2 (minuscules)
 * Couvre les 48 nations de la CdM 2026, noms anglais ET français.
 * Usage : getFlagUrl("France") → "https://flagcdn.com/24x18/fr.png"
 */

const FLAGS: Record<string, string> = {
  // ── CONCACAF ──────────────────────────────────────────────────────────
  'United States':       'us',
  'USA':                 'us',
  'États-Unis':          'us',
  'Canada':              'ca',
  'Mexico':              'mx',
  'Mexique':             'mx',
  'Costa Rica':          'cr',
  'Honduras':            'hn',
  'Panama':              'pa',
  'Jamaica':             'jm',
  'Jamaïque':            'jm',

  // ── CONMEBOL ─────────────────────────────────────────────────────────
  'Argentina':           'ar',
  'Argentine':           'ar',
  'Brazil':              'br',
  'Brésil':              'br',
  'Colombia':            'co',
  'Colombie':            'co',
  'Ecuador':             'ec',
  'Équateur':            'ec',
  'Uruguay':             'uy',
  'Venezuela':           've',
  'Paraguay':            'py',
  'Chile':               'cl',
  'Chili':               'cl',
  'Peru':                'pe',
  'Pérou':               'pe',
  'Bolivia':             'bo',

  // ── UEFA ─────────────────────────────────────────────────────────────
  'France':              'fr',
  'Germany':             'de',
  'Allemagne':           'de',
  'Spain':               'es',
  'Espagne':             'es',
  'England':             'gb-eng',
  'Angleterre':          'gb-eng',
  'Netherlands':         'nl',
  'Pays-Bas':            'nl',
  'Portugal':            'pt',
  'Belgium':             'be',
  'Belgique':            'be',
  'Croatia':             'hr',
  'Croatie':             'hr',
  'Italy':               'it',
  'Italie':              'it',
  'Serbia':              'rs',
  'Serbie':              'rs',
  'Switzerland':         'ch',
  'Suisse':              'ch',
  'Denmark':             'dk',
  'Danemark':            'dk',
  'Norway':              'no',
  'Norvège':             'no',
  'Poland':              'pl',
  'Pologne':             'pl',
  'Ukraine':             'ua',
  // Turquie — nom DB anglais avant script, nom français après
  'Turkey':              'tr',
  'Türkiye':             'tr',
  'Turquie':             'tr',
  // Suède — nom DB anglais avant script, nom français après
  'Sweden':              'se',
  'Suède':               'se',
  // Tchéquie — nom DB anglais avant script, nom français après
  'Czech Republic':      'cz',
  'Czechia':             'cz',
  'Tchéquie':            'cz',
  // Bosnie — nom DB anglais avant script, nom français après
  'Bosnia & Herzegovina': 'ba',
  'Bosnia and Herzegovina': 'ba',
  'Bosnia':              'ba',
  'Bosnie':              'ba',
  // Autres UEFA
  'Austria':             'at',
  'Autriche':            'at',
  'Hungary':             'hu',
  'Hongrie':             'hu',
  'Romania':             'ro',
  'Roumanie':            'ro',
  'Slovakia':            'sk',
  'Slovaquie':           'sk',
  'Albania':             'al',
  'Albanie':             'al',
  'Scotland':            'gb-sct',
  'Écosse':              'gb-sct',
  'Greece':              'gr',
  'Grèce':               'gr',
  'Iceland':             'is',
  'Islande':             'is',
  'Wales':               'gb-wls',
  'Pays de Galles':      'gb-wls',

  // ── CAF ──────────────────────────────────────────────────────────────
  'Morocco':             'ma',
  'Maroc':               'ma',
  'Senegal':             'sn',
  'Sénégal':             'sn',
  'Egypt':               'eg',
  'Égypte':              'eg',
  'Nigeria':             'ng',
  'Ivory Coast':         'ci',
  "Côte d'Ivoire":       'ci',
  'Cote d\'Ivoire':      'ci',
  'Cameroon':            'cm',
  'Cameroun':            'cm',
  'Tunisia':             'tn',
  'Tunisie':             'tn',
  'Algeria':             'dz',
  'Algérie':             'dz',
  'Ghana':               'gh',
  // Congo DR — nom DB anglais avant script, nom français après
  'Congo DR':            'cd',
  'DR Congo':            'cd',
  'Democratic Republic of Congo': 'cd',
  'RD Congo':            'cd',
  'South Africa':        'za',
  'Afrique du Sud':      'za',
  'Mali':                'ml',
  'Guinea':              'gn',
  'Guinée':              'gn',
  'Tanzania':            'tz',
  'Tanzanie':            'tz',
  'Zambia':              'zm',
  'Zambie':              'zm',

  // ── AFC ──────────────────────────────────────────────────────────────
  'Japan':               'jp',
  'Japon':               'jp',
  'South Korea':         'kr',
  'Korea Republic':      'kr',
  'Corée du Sud':        'kr',
  'Saudi Arabia':        'sa',
  'Arabie Saoudite':     'sa',
  'Iran':                'ir',
  'Australia':           'au',
  'Australie':           'au',
  'Qatar':               'qa',
  'Uzbekistan':          'uz',
  'Ouzbékistan':         'uz',
  'Jordan':              'jo',
  'Jordanie':            'jo',
  // Irak — nom DB anglais avant script, nom français après
  'Iraq':                'iq',
  'Irak':                'iq',
  'China':               'cn',
  'Chine':               'cn',
  'Oman':                'om',
  'United Arab Emirates': 'ae',
  'Émirats arabes unis': 'ae',
  'India':               'in',
  'Inde':                'in',
  'Indonesia':           'id',
  'Indonésie':           'id',

  // ── OFC ──────────────────────────────────────────────────────────────
  'New Zealand':         'nz',
  'Nouvelle-Zélande':    'nz',

  // ── Divers / CONCACAF étendu ──────────────────────────────────────────
  'Cape Verde Islands':  'cv',
  'Cape Verde':          'cv',
  'Cabo Verde':          'cv',
  'Curaçao':             'cw',
  'Haiti':               'ht',
  'Haïti':               'ht',
  // Variante API-Football pour l'Iran
  'IR Iran':             'ir',

  // ── Équipes TBD (résultat playoff inconnu) ───────────────────────────
  // Code vide = connu mais sans drapeau à afficher
  'TBD':                 '',
}

/** Retourne le code ISO alpha-2 pour un nom d'équipe, ou null si inconnu ou sans drapeau. */
export function getCountryCode(teamName: string): string | null {
  const code = FLAGS[teamName]
  if (code === undefined || code === '') return null
  return code
}

/** Retourne l'URL flagcdn.com (SVG, résolution infinie) pour un nom d'équipe. */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export function getFlagUrl(teamName: string, size?: '24x18' | '40x30' | '16x12'): string | null {
  const code = getCountryCode(teamName)
  if (!code) return null
  return `https://flagcdn.com/${code}.svg`
}

/** Retourne true si le nom est explicitement référencé dans FLAGS (même sans drapeau comme TBD). */
export function isKnownTeam(teamName: string): boolean {
  return teamName in FLAGS
}

// ── Couleurs maillots domicile ────────────────────────────────────────────────
// primary = couleur dominante, secondary = couleur de contraste (col, bandes)

export const TEAM_COLORS: Record<string, { primary: string; secondary: string }> = {
  // ── Valeurs précises fournies ──────────────────────────────────────────────
  'France':                 { primary: '#1D2A57', secondary: '#EF3340' },
  'Brazil':                 { primary: '#FFDF00', secondary: '#009C3B' },
  'England':                { primary: '#FFFFFF', secondary: '#CE1124' },
  'Germany':                { primary: '#FFFFFF', secondary: '#000000' },
  'Spain':                  { primary: '#AA151B', secondary: '#F1BF00' },
  'Portugal':               { primary: '#006600', secondary: '#CC0000' },
  'Argentina':              { primary: '#74ACDF', secondary: '#FFFFFF' },
  'Netherlands':            { primary: '#FF6600', secondary: '#FFFFFF' },
  'Belgium':                { primary: '#000000', secondary: '#EF3340' },
  'Croatia':                { primary: '#FF0000', secondary: '#FFFFFF' },
  'Morocco':                { primary: '#C1272D', secondary: '#006233' },
  'Senegal':                { primary: '#00853F', secondary: '#FDEF42' },
  'Japan':                  { primary: '#000080', secondary: '#FFFFFF' },
  'South Korea':            { primary: '#FFFFFF', secondary: '#003478' },
  'USA':                    { primary: '#002868', secondary: '#BF0A30' },
  'Mexico':                 { primary: '#006847', secondary: '#CE1126' },
  'Canada':                 { primary: '#FF0000', secondary: '#FFFFFF' },
  'Australia':              { primary: '#FFD700', secondary: '#00843D' },
  'Switzerland':            { primary: '#FF0000', secondary: '#FFFFFF' },
  'Uruguay':                { primary: '#5FFFFF', secondary: '#FFFFFF' },
  'Colombia':               { primary: '#FCD116', secondary: '#003087' },
  'Ecuador':                { primary: '#FFD100', secondary: '#003087' },
  'Panama':                 { primary: '#FFFFFF', secondary: '#DA121A' },
  'Ghana':                  { primary: '#006B3F', secondary: '#FCD116' },
  'Tunisia':                { primary: '#E70013', secondary: '#FFFFFF' },
  'Egypt':                  { primary: '#CE1126', secondary: '#FFFFFF' },
  'Algeria':                { primary: '#006233', secondary: '#FFFFFF' },
  'Norway':                 { primary: '#EF2B2D', secondary: '#002868' },
  'Sweden':                 { primary: '#006AA7', secondary: '#FECC02' },
  'Austria':                { primary: '#ED2939', secondary: '#FFFFFF' },
  'Scotland':               { primary: '#003865', secondary: '#FFFFFF' },
  'Czech Republic':         { primary: '#D7162B', secondary: '#FFFFFF' },
  'Türkiye':                { primary: '#E30A17', secondary: '#FFFFFF' },
  'Poland':                 { primary: '#FFFFFF', secondary: '#DC143C' },
  'Serbia':                 { primary: '#C6363C', secondary: '#0C4076' },
  'Ukraine':                { primary: '#005BBB', secondary: '#FFD500' },
  'Iran':                   { primary: '#239F40', secondary: '#FFFFFF' },
  'Saudi Arabia':           { primary: '#006C35', secondary: '#FFFFFF' },
  'Qatar':                  { primary: '#8D1B3D', secondary: '#FFFFFF' },
  'Iraq':                   { primary: '#CE1126', secondary: '#007A3D' },
  'Jordan':                 { primary: '#007A3D', secondary: '#FFFFFF' },
  'Uzbekistan':             { primary: '#1EB53A', secondary: '#0099B5' },
  'New Zealand':            { primary: '#FFFFFF', secondary: '#000000' },
  'Bosnia & Herzegovina':   { primary: '#003DA5', secondary: '#FFCD00' },
  'Ivory Coast':            { primary: '#F77F00', secondary: '#009A44' },
  'Congo DR':               { primary: '#007FFF', secondary: '#F7D618' },
  'Cape Verde Islands':     { primary: '#003893', secondary: '#CF2027' },
  'Haiti':                  { primary: '#00209F', secondary: '#D21034' },
  'Curaçao':                { primary: '#003DA5', secondary: '#F7D618' },
  'South Africa':           { primary: '#007A4D', secondary: '#FFB81C' },
  'Paraguay':               { primary: '#D52B1E', secondary: '#FFFFFF' },

  // ── Alias API-Football / variantes ────────────────────────────────────────
  'United States':          { primary: '#002868', secondary: '#BF0A30' },
  'Korea Republic':         { primary: '#FFFFFF', secondary: '#003478' },
  'IR Iran':                { primary: '#239F40', secondary: '#FFFFFF' },
  'Turkey':                 { primary: '#E30A17', secondary: '#FFFFFF' },
  'Czechia':                { primary: '#D7162B', secondary: '#FFFFFF' },
  'Bosnia and Herzegovina': { primary: '#003DA5', secondary: '#FFCD00' },
  "Côte d'Ivoire":          { primary: '#F77F00', secondary: '#009A44' },
  "Cote d'Ivoire":          { primary: '#F77F00', secondary: '#009A44' },
  'DR Congo':               { primary: '#007FFF', secondary: '#F7D618' },
  'Cape Verde':             { primary: '#003893', secondary: '#CF2027' },
  'Cabo Verde':             { primary: '#003893', secondary: '#CF2027' },
  'Haïti':                  { primary: '#00209F', secondary: '#D21034' },

  // ── Autres nations qualifiées ─────────────────────────────────────────────
  'Italy':                  { primary: '#003399', secondary: '#FFFFFF' },
  'Denmark':                { primary: '#CC0001', secondary: '#FFFFFF' },
  'Hungary':                { primary: '#CC0001', secondary: '#FFFFFF' },
  'Romania':                { primary: '#FFD700', secondary: '#003DA5' },
  'Slovakia':               { primary: '#003DA5', secondary: '#FFFFFF' },
  'Albania':                { primary: '#CC0001', secondary: '#000000' },
  'Greece':                 { primary: '#003DA5', secondary: '#FFFFFF' },
  'Iceland':                { primary: '#003DA5', secondary: '#FFFFFF' },
  'Wales':                  { primary: '#CC0001', secondary: '#003DA5' },
  'Nigeria':                { primary: '#008751', secondary: '#FFFFFF' },
  'Cameroon':               { primary: '#007A5E', secondary: '#CE1126' },
  'Mali':                   { primary: '#009A44', secondary: '#FFFFFF' },
  'Guinea':                 { primary: '#CC0001', secondary: '#FFD700' },
  'Tanzania':               { primary: '#1EB53A', secondary: '#003DA5' },
  'Zambia':                 { primary: '#198A00', secondary: '#EF7D00' },
  'China':                  { primary: '#CC0001', secondary: '#FFD700' },
  'Indonesia':              { primary: '#CC0001', secondary: '#FFFFFF' },
  'India':                  { primary: '#003DA5', secondary: '#FF9933' },
  'Oman':                   { primary: '#CC0001', secondary: '#FFFFFF' },
  'United Arab Emirates':   { primary: '#CC0001', secondary: '#000000' },
  'Costa Rica':             { primary: '#CC0000', secondary: '#001489' },
  'Honduras':               { primary: '#0038A8', secondary: '#FFFFFF' },
  'Jamaica':                { primary: '#FED100', secondary: '#000000' },
  'Venezuela':              { primary: '#CF142B', secondary: '#CF9B27' },
  'Chile':                  { primary: '#CC0001', secondary: '#FFFFFF' },
  'Peru':                   { primary: '#FFFFFF', secondary: '#CC0001' },
  'Bolivia':                { primary: '#D62718', secondary: '#FFD700' },
}

// ── Codes FIFA 3 lettres ──────────────────────────────────────────────────────
// Clés en anglais (noms DB). Usage : FIFA_CODE[team] ?? team.slice(0,3).toUpperCase()

export const FIFA_CODE: Record<string, string> = {
  // CONCACAF
  'United States':          'USA',
  'USA':                    'USA',
  'Canada':                 'CAN',
  'Mexico':                 'MEX',
  'Costa Rica':             'CRC',
  'Honduras':               'HON',
  'Panama':                 'PAN',
  'Jamaica':                'JAM',

  // CONMEBOL
  'Argentina':              'ARG',
  'Brazil':                 'BRA',
  'Colombia':               'COL',
  'Ecuador':                'ECU',
  'Uruguay':                'URU',
  'Venezuela':              'VEN',
  'Paraguay':               'PAR',
  'Chile':                  'CHI',
  'Peru':                   'PER',
  'Bolivia':                'BOL',

  // UEFA
  'France':                 'FRA',
  'Germany':                'GER',
  'Spain':                  'ESP',
  'England':                'ENG',
  'Netherlands':            'NED',
  'Portugal':               'POR',
  'Belgium':                'BEL',
  'Croatia':                'CRO',
  'Italy':                  'ITA',
  'Serbia':                 'SRB',
  'Switzerland':            'SUI',
  'Denmark':                'DEN',
  'Norway':                 'NOR',
  'Poland':                 'POL',
  'Ukraine':                'UKR',
  'Turkey':                 'TUR',
  'Türkiye':                'TUR',
  'Sweden':                 'SWE',
  'Czech Republic':         'CZE',
  'Czechia':                'CZE',
  'Bosnia & Herzegovina':   'BIH',
  'Bosnia and Herzegovina': 'BIH',
  'Austria':                'AUT',
  'Hungary':                'HUN',
  'Romania':                'ROU',
  'Slovakia':               'SVK',
  'Albania':                'ALB',
  'Scotland':               'SCO',
  'Greece':                 'GRE',
  'Iceland':                'ISL',
  'Wales':                  'WAL',

  // CAF
  'Morocco':                'MAR',
  'Senegal':                'SEN',
  'Egypt':                  'EGY',
  'Nigeria':                'NGA',
  'Ivory Coast':            'CIV',
  'Cameroon':               'CMR',
  'Tunisia':                'TUN',
  'Algeria':                'ALG',
  'Ghana':                  'GHA',
  'Congo DR':               'COD',
  'DR Congo':               'COD',
  'South Africa':           'RSA',
  'Mali':                   'MLI',
  'Guinea':                 'GUI',
  'Tanzania':               'TAN',
  'Cape Verde Islands':     'CPV',
  'Cape Verde':             'CPV',
  'Cabo Verde':             'CPV',
  'Curaçao':                'CUW',
  'Haiti':                  'HAI',
  'Zambia':                 'ZAM',

  // AFC
  'Japan':                  'JPN',
  'South Korea':            'KOR',
  'Korea Republic':         'KOR',
  'Saudi Arabia':           'KSA',
  'Iran':                   'IRN',
  'IR Iran':                'IRN',
  'Australia':              'AUS',
  'Qatar':                  'QAT',
  'Uzbekistan':             'UZB',
  'Jordan':                 'JOR',
  'Iraq':                   'IRQ',
  'China':                  'CHN',
  'Indonesia':              'IDN',
  'India':                  'IND',
  'Oman':                   'OMA',
  'United Arab Emirates':   'UAE',

  // OFC
  'New Zealand':            'NZL',
}

// ── Traductions FR ────────────────────────────────────────────────────────────
// Les noms en base restent en anglais — uniquement l'affichage change.
// Usage : TEAM_NAME_FR[team] ?? team

export const TEAM_NAME_FR: Record<string, string> = {
  // CONCACAF
  'USA':                    'États-Unis',
  'United States':          'États-Unis',
  'Mexico':                 'Mexique',
  'Canada':                 'Canada',
  'Costa Rica':             'Costa Rica',
  'Honduras':               'Honduras',
  'Panama':                 'Panama',
  'Jamaica':                'Jamaïque',

  // CONMEBOL
  'Argentina':              'Argentine',
  'Brazil':                 'Brésil',
  'Colombia':               'Colombie',
  'Ecuador':                'Équateur',
  'Uruguay':                'Uruguay',
  'Venezuela':              'Venezuela',
  'Paraguay':               'Paraguay',
  'Chile':                  'Chili',
  'Peru':                   'Pérou',
  'Bolivia':                'Bolivie',

  // UEFA
  'France':                 'France',
  'Germany':                'Allemagne',
  'Spain':                  'Espagne',
  'England':                'Angleterre',
  'Netherlands':            'Pays-Bas',
  'Portugal':               'Portugal',
  'Belgium':                'Belgique',
  'Croatia':                'Croatie',
  'Italy':                  'Italie',
  'Serbia':                 'Serbie',
  'Switzerland':            'Suisse',
  'Denmark':                'Danemark',
  'Norway':                 'Norvège',
  'Poland':                 'Pologne',
  'Ukraine':                'Ukraine',
  'Turkey':                 'Turquie',
  'Türkiye':                'Turquie',
  'Sweden':                 'Suède',
  'Czech Republic':         'Tchéquie',
  'Czechia':                'Tchéquie',
  'Bosnia & Herzegovina':   'Bosnie-Herzégovine',
  'Bosnia and Herzegovina': 'Bosnie-Herzégovine',
  'Austria':                'Autriche',
  'Hungary':                'Hongrie',
  'Romania':                'Roumanie',
  'Slovakia':               'Slovaquie',
  'Albania':                'Albanie',
  'Scotland':               'Écosse',
  'Greece':                 'Grèce',
  'Iceland':                'Islande',
  'Wales':                  'Pays de Galles',

  // CAF
  'Morocco':                'Maroc',
  'Senegal':                'Sénégal',
  'Egypt':                  'Égypte',
  'Nigeria':                'Nigeria',
  'Ivory Coast':            "Côte d'Ivoire",
  'Cameroon':               'Cameroun',
  'Tunisia':                'Tunisie',
  'Algeria':                'Algérie',
  'Ghana':                  'Ghana',
  'Congo DR':               'RD Congo',
  'DR Congo':               'RD Congo',
  'South Africa':           'Afrique du Sud',
  'Mali':                   'Mali',
  'Guinea':                 'Guinée',
  'Tanzania':               'Tanzanie',
  'Cape Verde Islands':     'Cap-Vert',
  'Cape Verde':             'Cap-Vert',
  'Cabo Verde':             'Cap-Vert',
  'Curaçao':                'Curaçao',
  'Haiti':                  'Haïti',
  'Haïti':                  'Haïti',
  'IR Iran':                'Iran',

  // AFC
  'Japan':                  'Japon',
  'South Korea':            'Corée du Sud',
  'Korea Republic':         'Corée du Sud',
  'Saudi Arabia':           'Arabie Saoudite',
  'Iran':                   'Iran',
  'Australia':              'Australie',
  'Qatar':                  'Qatar',
  'Uzbekistan':             'Ouzbékistan',
  'Jordan':                 'Jordanie',
  'Iraq':                   'Irak',
  'China':                  'Chine',
  'Indonesia':              'Indonésie',
  'India':                  'Inde',
  'Oman':                   'Oman',
  'United Arab Emirates':   'Émirats arabes unis',

  // OFC
  'New Zealand':            'Nouvelle-Zélande',
}
